// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3Tanenbaum {
  // https://rollux.tanenbaum.io/address/0x86B02a0513d883dbEEF1ECF9c54aAa933f014759
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x86B02a0513d883dbEEF1ECF9c54aAa933f014759);

  // https://rollux.tanenbaum.io/address/0xAFB1204855aed95623E1a6d3F0cf52B3d08DF684
  IPool internal constant POOL = IPool(0xAFB1204855aed95623E1a6d3F0cf52B3d08DF684);

  // https://rollux.tanenbaum.io/address/0x1B45DdD14Ba6Eb8f00f2496cf60068AFEc11092F
  address internal constant POOL_IMPL = 0x1B45DdD14Ba6Eb8f00f2496cf60068AFEc11092F;

  // https://rollux.tanenbaum.io/address/0x30ff4ea8BFf60A9bDe0054293FaFa2CaB01DF625
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x30ff4ea8BFf60A9bDe0054293FaFa2CaB01DF625);

  // https://rollux.tanenbaum.io/address/0x3eD5FcD97f7aEe70fD0128758973a9F01210af0D
  address internal constant POOL_CONFIGURATOR_IMPL = 0x3eD5FcD97f7aEe70fD0128758973a9F01210af0D;

  // https://rollux.tanenbaum.io/address/0x5BF633657766956dDBbF0e9e6A16e7ff3783308d
  IAaveOracle internal constant ORACLE = IAaveOracle(0x5BF633657766956dDBbF0e9e6A16e7ff3783308d);

  // https://rollux.tanenbaum.io/address/0x5A7e125998dF43d462cB42e0e48A6eC3D02e661C
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x5A7e125998dF43d462cB42e0e48A6eC3D02e661C);

  // https://rollux.tanenbaum.io/address/0xb2eCb1F86c773c2A1cDfaC050CfF1E4912335a8c
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xb2eCb1F86c773c2A1cDfaC050CfF1E4912335a8c);

  // https://rollux.tanenbaum.io/address/0xD2b48B055239B94e1A2D080BA1C9D98c18F54dB8
  address internal constant ACL_ADMIN = 0xD2b48B055239B94e1A2D080BA1C9D98c18F54dB8;

  // https://rollux.tanenbaum.io/address/0x514207067DE90a88F37236E404506d341D1ee933
  ICollector internal constant COLLECTOR = ICollector(0x514207067DE90a88F37236E404506d341D1ee933);

  // https://rollux.tanenbaum.io/address/0x385A44D09f130397844B0d4cC7d4FAecfb3E5Aa1
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x385A44D09f130397844B0d4cC7d4FAecfb3E5Aa1;

  // https://rollux.tanenbaum.io/address/0x065d574C2E785b2AD8D45B01B8dA14c84f5586D1
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x065d574C2E785b2AD8D45B01B8dA14c84f5586D1;

  // https://rollux.tanenbaum.io/address/0x7352195612De3c0f34B9603A30B676BcceabbEB4
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x7352195612De3c0f34B9603A30B676BcceabbEB4;

  // https://rollux.tanenbaum.io/address/0x8AaA16A67a9e58c9Cb568545be7369529D656084
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x8AaA16A67a9e58c9Cb568545be7369529D656084;

  // https://rollux.tanenbaum.io/address/0xe25C221501153213f1383B086d5Be0670fecA2E6
  address internal constant EMISSION_MANAGER = 0xe25C221501153213f1383B086d5Be0670fecA2E6;

  // https://rollux.tanenbaum.io/address/0xbAbE69ba2292e7297480282390ee712d10B2a06E
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xbAbE69ba2292e7297480282390ee712d10B2a06E;

  // https://rollux.tanenbaum.io/address/0x885912f4e648ff71AB9914295eCC7FD7BDF1F2Fe
  address internal constant UI_POOL_DATA_PROVIDER = 0x885912f4e648ff71AB9914295eCC7FD7BDF1F2Fe;

  // https://rollux.tanenbaum.io/address/0x2979f1dfec495A6f661D03aa49bE05514Eb33FFD
  address internal constant WALLET_BALANCE_PROVIDER = 0x2979f1dfec495A6f661D03aa49bE05514Eb33FFD;

  // https://rollux.tanenbaum.io/address/0xe7036E7258Ccc423123eD24358f9861Fb54f323D
  address internal constant WETH_GATEWAY = 0xe7036E7258Ccc423123eD24358f9861Fb54f323D;
}

library AaveV3TanenbaumAssets {
  // https://rollux.tanenbaum.io/address/0xfA600253bB6fE44CEAb0538000a8448807e50c85
  address internal constant RBTC_UNDERLYING = 0xfA600253bB6fE44CEAb0538000a8448807e50c85;

  uint8 internal constant RBTC_DECIMALS = 8;

  // https://rollux.tanenbaum.io/address/0xefd0387d704274f23Cd9B57e2B6E242B8333424E
  address internal constant RBTC_A_TOKEN = 0xefd0387d704274f23Cd9B57e2B6E242B8333424E;

  // https://rollux.tanenbaum.io/address/0x9862f7F5329dF7654df648C57e79e0fDb81e0AC7
  address internal constant RBTC_V_TOKEN = 0x9862f7F5329dF7654df648C57e79e0fDb81e0AC7;

  // https://rollux.tanenbaum.io/address/0xce5DE210258E4FF968f1029b02dA32C5f8a629B2
  address internal constant RBTC_S_TOKEN = 0xce5DE210258E4FF968f1029b02dA32C5f8a629B2;

  // https://rollux.tanenbaum.io/address/0x5eD0B6460356f28F469aA30E402084445cD84E65
  address internal constant RBTC_ORACLE = 0x5eD0B6460356f28F469aA30E402084445cD84E65;

  // https://rollux.tanenbaum.io/address/0xeAAE0C369D178e32db1600265c97161892a81dC6
  address internal constant RBTC_INTEREST_RATE_STRATEGY =
    0xeAAE0C369D178e32db1600265c97161892a81dC6;

  // https://rollux.tanenbaum.io/address/0x5eD4813824E5e2bAF9BBC211121b21aB38E02522
  address internal constant RWETH_UNDERLYING = 0x5eD4813824E5e2bAF9BBC211121b21aB38E02522;

  uint8 internal constant RWETH_DECIMALS = 18;

  // https://rollux.tanenbaum.io/address/0x11BDe9A9282C548AB2Ae52af68B1dfCb929eAB16
  address internal constant RWETH_A_TOKEN = 0x11BDe9A9282C548AB2Ae52af68B1dfCb929eAB16;

  // https://rollux.tanenbaum.io/address/0xBc725e94873Bf2E053cdA824A070626Da50f96BE
  address internal constant RWETH_V_TOKEN = 0xBc725e94873Bf2E053cdA824A070626Da50f96BE;

  // https://rollux.tanenbaum.io/address/0xcE92918f9c31095e91716Fc3862b41A77a7CF956
  address internal constant RWETH_S_TOKEN = 0xcE92918f9c31095e91716Fc3862b41A77a7CF956;

  // https://rollux.tanenbaum.io/address/0x7C1cB41C2C852D96c06f58a47b36e068C9cf1E4a
  address internal constant RWETH_ORACLE = 0x7C1cB41C2C852D96c06f58a47b36e068C9cf1E4a;

  // https://rollux.tanenbaum.io/address/0xeAAE0C369D178e32db1600265c97161892a81dC6
  address internal constant RWETH_INTEREST_RATE_STRATEGY =
    0xeAAE0C369D178e32db1600265c97161892a81dC6;

  // https://rollux.tanenbaum.io/address/0xcAc0759160d57A33D332Ed36a555C10957694407
  address internal constant WTSYS_UNDERLYING = 0xcAc0759160d57A33D332Ed36a555C10957694407;

  uint8 internal constant WTSYS_DECIMALS = 18;

  // https://rollux.tanenbaum.io/address/0x217810F41a02BdCa9Fd934f464d1d79EF8779FbB
  address internal constant WTSYS_A_TOKEN = 0x217810F41a02BdCa9Fd934f464d1d79EF8779FbB;

  // https://rollux.tanenbaum.io/address/0x1071679bFD1fC02c1aFCc9eb10247f759664AE96
  address internal constant WTSYS_V_TOKEN = 0x1071679bFD1fC02c1aFCc9eb10247f759664AE96;

  // https://rollux.tanenbaum.io/address/0xb1eAB82DaB85F4Acd1B3941be7C0e8E7b2FF2af8
  address internal constant WTSYS_S_TOKEN = 0xb1eAB82DaB85F4Acd1B3941be7C0e8E7b2FF2af8;

  // https://rollux.tanenbaum.io/address/0x42cF8Fd3A114E3ed807379c6E4e6E7f9A30AC561
  address internal constant WTSYS_ORACLE = 0x42cF8Fd3A114E3ed807379c6E4e6E7f9A30AC561;

  // https://rollux.tanenbaum.io/address/0xeAAE0C369D178e32db1600265c97161892a81dC6
  address internal constant WTSYS_INTEREST_RATE_STRATEGY =
    0xeAAE0C369D178e32db1600265c97161892a81dC6;

  // https://rollux.tanenbaum.io/address/0x9D973BAc12BB62A55be0F9f7Ad201eEA4f9B8428
  address internal constant RUSDT_UNDERLYING = 0x9D973BAc12BB62A55be0F9f7Ad201eEA4f9B8428;

  uint8 internal constant RUSDT_DECIMALS = 6;

  // https://rollux.tanenbaum.io/address/0x84BBA6B62fD5AfCe151E30f7B44e89dE0DfDb875
  address internal constant RUSDT_A_TOKEN = 0x84BBA6B62fD5AfCe151E30f7B44e89dE0DfDb875;

  // https://rollux.tanenbaum.io/address/0x8C530f47Ee9F2eeEDbB940983a38E879c428C178
  address internal constant RUSDT_V_TOKEN = 0x8C530f47Ee9F2eeEDbB940983a38E879c428C178;

  // https://rollux.tanenbaum.io/address/0xb0b61Aaf77b966e3EC951F5620efDc1a3F08875F
  address internal constant RUSDT_S_TOKEN = 0xb0b61Aaf77b966e3EC951F5620efDc1a3F08875F;

  // https://rollux.tanenbaum.io/address/0xcC34C2094C13ee22047B16BD31a25ABc6972d365
  address internal constant RUSDT_ORACLE = 0xcC34C2094C13ee22047B16BD31a25ABc6972d365;

  // https://rollux.tanenbaum.io/address/0xDA312C2678F40BE22e3D3202fAc51d9d619D2Df8
  address internal constant RUSDT_INTEREST_RATE_STRATEGY =
    0xDA312C2678F40BE22e3D3202fAc51d9d619D2Df8;

  // https://rollux.tanenbaum.io/address/0xf111Aa386823C4CF33F349597f1E772973Ac0913
  address internal constant RUSDC_UNDERLYING = 0xf111Aa386823C4CF33F349597f1E772973Ac0913;

  uint8 internal constant RUSDC_DECIMALS = 6;

  // https://rollux.tanenbaum.io/address/0x7abaE9c615eAE610c1a267d36cfEa51Ec915D169
  address internal constant RUSDC_A_TOKEN = 0x7abaE9c615eAE610c1a267d36cfEa51Ec915D169;

  // https://rollux.tanenbaum.io/address/0x8177b7cc5b4a60E475F19512dC219d4Dce030Fcc
  address internal constant RUSDC_V_TOKEN = 0x8177b7cc5b4a60E475F19512dC219d4Dce030Fcc;

  // https://rollux.tanenbaum.io/address/0x07101B95a0B6b150C79e83e2d961b86667c94037
  address internal constant RUSDC_S_TOKEN = 0x07101B95a0B6b150C79e83e2d961b86667c94037;

  // https://rollux.tanenbaum.io/address/0x128421A48C3E9AE386da855F10b825aD84701014
  address internal constant RUSDC_ORACLE = 0x128421A48C3E9AE386da855F10b825aD84701014;

  // https://rollux.tanenbaum.io/address/0xDA312C2678F40BE22e3D3202fAc51d9d619D2Df8
  address internal constant RUSDC_INTEREST_RATE_STRATEGY =
    0xDA312C2678F40BE22e3D3202fAc51d9d619D2Df8;

  // https://rollux.tanenbaum.io/address/0xD451237dceE3395B63d84FF0DDC0a4dbCf005Cc1
  address internal constant RPSYS_UNDERLYING = 0xD451237dceE3395B63d84FF0DDC0a4dbCf005Cc1;

  uint8 internal constant RPSYS_DECIMALS = 18;

  // https://rollux.tanenbaum.io/address/0xfcF41bac2A631eb0CaF52465b93B45a271b55841
  address internal constant RPSYS_A_TOKEN = 0xfcF41bac2A631eb0CaF52465b93B45a271b55841;

  // https://rollux.tanenbaum.io/address/0x257e3150E03727726D573d10873E18e93C4934c9
  address internal constant RPSYS_V_TOKEN = 0x257e3150E03727726D573d10873E18e93C4934c9;

  // https://rollux.tanenbaum.io/address/0xc779bA44d3EB052bc4e6e5c9aa74D7Ee535aDFA1
  address internal constant RPSYS_S_TOKEN = 0xc779bA44d3EB052bc4e6e5c9aa74D7Ee535aDFA1;

  // https://rollux.tanenbaum.io/address/0x42cF8Fd3A114E3ed807379c6E4e6E7f9A30AC561
  address internal constant RPSYS_ORACLE = 0x42cF8Fd3A114E3ed807379c6E4e6E7f9A30AC561;

  // https://rollux.tanenbaum.io/address/0xeAAE0C369D178e32db1600265c97161892a81dC6
  address internal constant RPSYS_INTEREST_RATE_STRATEGY =
    0xeAAE0C369D178e32db1600265c97161892a81dC6;
}

library AaveV3TanenbaumEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant STABLECOINS = 1;
}
