// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3Tinkle {
  // https://iotexscan.io/address/0xF688EE64450B3a9024CD7922a5E88D11e85E9861
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xF688EE64450B3a9024CD7922a5E88D11e85E9861);

  // https://iotexscan.io/address/0x593Cbb4DCb8DBD2E3A639dBc379C6658E0aF4897
  IPool internal constant POOL = IPool(0x593Cbb4DCb8DBD2E3A639dBc379C6658E0aF4897);

  // https://iotexscan.io/address/0x0aea5980c572CA8Fe782653ED56254f947FAC848
  address internal constant POOL_IMPL = 0x0aea5980c572CA8Fe782653ED56254f947FAC848;

  // https://iotexscan.io/address/0x7080b76893b3D50Ceb283662dfCa37F6950692e6
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x7080b76893b3D50Ceb283662dfCa37F6950692e6);

  // https://iotexscan.io/address/0x182C2F735Ca4534701296F9C64170aBB9aCA22d3
  address internal constant POOL_CONFIGURATOR_IMPL = 0x182C2F735Ca4534701296F9C64170aBB9aCA22d3;

  // https://iotexscan.io/address/0xdC4A66bD85F36aF5CaD9DeD546C25e1d2b0217eB
  IAaveOracle internal constant ORACLE = IAaveOracle(0xdC4A66bD85F36aF5CaD9DeD546C25e1d2b0217eB);

  // https://iotexscan.io/address/0x86B02a0513d883dbEEF1ECF9c54aAa933f014759
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x86B02a0513d883dbEEF1ECF9c54aAa933f014759);

  // https://iotexscan.io/address/0x1F747321f9709Ad05d416Ef0eE97323E77B5963A
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x1F747321f9709Ad05d416Ef0eE97323E77B5963A);

  // https://iotexscan.io/address/0xD2b48B055239B94e1A2D080BA1C9D98c18F54dB8
  address internal constant ACL_ADMIN = 0xD2b48B055239B94e1A2D080BA1C9D98c18F54dB8;

  // https://iotexscan.io/address/0xc972E5d32DDB1d6894A5f59229C0733B2eBaB993
  ICollector internal constant COLLECTOR = ICollector(0xc972E5d32DDB1d6894A5f59229C0733B2eBaB993);

  // https://iotexscan.io/address/0x9EBf4a626D521f338d50e96E96b00250BFe9d9ae
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x9EBf4a626D521f338d50e96E96b00250BFe9d9ae;

  // https://iotexscan.io/address/0x8AaA16A67a9e58c9Cb568545be7369529D656084
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x8AaA16A67a9e58c9Cb568545be7369529D656084;

  // https://iotexscan.io/address/0x7e639E97AC90e506119C9d448f6B15007dccb519
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x7e639E97AC90e506119C9d448f6B15007dccb519;

  // https://iotexscan.io/address/0xeAAE0C369D178e32db1600265c97161892a81dC6
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xeAAE0C369D178e32db1600265c97161892a81dC6;

  // https://iotexscan.io/address/0x64589b6b7128FE1E6F9cA22a926d8A5aA346c5A4
  address internal constant EMISSION_MANAGER = 0x64589b6b7128FE1E6F9cA22a926d8A5aA346c5A4;

  // https://iotexscan.io/address/0xCcdc1e940307b727c891ffe67A44eEfB7e939545
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xCcdc1e940307b727c891ffe67A44eEfB7e939545;

  // https://iotexscan.io/address/0x4dc6F79EF3F655BC5ee7AebC37F15beA38aFAA39
  address internal constant UI_POOL_DATA_PROVIDER = 0x4dc6F79EF3F655BC5ee7AebC37F15beA38aFAA39;

  // https://iotexscan.io/address/0x01C784eb4Dc264eA8093f263570B839d7B9b4E64
  address internal constant WALLET_BALANCE_PROVIDER = 0x01C784eb4Dc264eA8093f263570B839d7B9b4E64;

  // https://iotexscan.io/address/0x3153F3073f1621c3b0b9d7FB0594184E3a510439
  address internal constant WETH_GATEWAY = 0x3153F3073f1621c3b0b9d7FB0594184E3a510439;
}

library AaveV3TinkleAssets {
  // https://iotexscan.io/address/0x4BCE326a702Ad7bE98131BEe60c177d1Ff8903B8
  address internal constant RBTC_UNDERLYING = 0x4BCE326a702Ad7bE98131BEe60c177d1Ff8903B8;

  uint8 internal constant RBTC_DECIMALS = 8;

  // https://iotexscan.io/address/0x04ff764A8C454B9d2725623B73260Df244B14DBd
  address internal constant RBTC_A_TOKEN = 0x04ff764A8C454B9d2725623B73260Df244B14DBd;

  // https://iotexscan.io/address/0x9F699f92d06d768426BEE63e1603a242d9DD3a69
  address internal constant RBTC_V_TOKEN = 0x9F699f92d06d768426BEE63e1603a242d9DD3a69;

  // https://iotexscan.io/address/0x426e316fc8e0a3D896C5BA9b216424c6abD9Cb17
  address internal constant RBTC_S_TOKEN = 0x426e316fc8e0a3D896C5BA9b216424c6abD9Cb17;

  // https://iotexscan.io/address/0xBDA0F8976c535B715D1b05CFc87F2966BdA8AD6B
  address internal constant RBTC_ORACLE = 0xBDA0F8976c535B715D1b05CFc87F2966BdA8AD6B;

  // https://iotexscan.io/address/0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3
  address internal constant RBTC_INTEREST_RATE_STRATEGY =
    0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3;

  // https://iotexscan.io/address/0xA9d1307b8fEdC8BA6E5A2898594039840DEc659D
  address internal constant RWETH_UNDERLYING = 0xA9d1307b8fEdC8BA6E5A2898594039840DEc659D;

  uint8 internal constant RWETH_DECIMALS = 18;

  // https://iotexscan.io/address/0xE7e97F34Dc96e79EF23e7A04D2Eb7513Db089138
  address internal constant RWETH_A_TOKEN = 0xE7e97F34Dc96e79EF23e7A04D2Eb7513Db089138;

  // https://iotexscan.io/address/0x721c494993D2C19e17523e9026AF99aC30D50273
  address internal constant RWETH_V_TOKEN = 0x721c494993D2C19e17523e9026AF99aC30D50273;

  // https://iotexscan.io/address/0x6aE5F83AF82AA503d726Fc8eeb2B8AF02BE0f124
  address internal constant RWETH_S_TOKEN = 0x6aE5F83AF82AA503d726Fc8eeb2B8AF02BE0f124;

  // https://iotexscan.io/address/0x5A7e125998dF43d462cB42e0e48A6eC3D02e661C
  address internal constant RWETH_ORACLE = 0x5A7e125998dF43d462cB42e0e48A6eC3D02e661C;

  // https://iotexscan.io/address/0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3
  address internal constant RWETH_INTEREST_RATE_STRATEGY =
    0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3;

  // https://iotexscan.io/address/0x60b393Bd3995238e2B985e046E823cb06f687263
  address internal constant WTSYS_UNDERLYING = 0x60b393Bd3995238e2B985e046E823cb06f687263;

  uint8 internal constant WTSYS_DECIMALS = 18;

  // https://iotexscan.io/address/0x2f259e071Ad31684C61dF1df320e624020d88423
  address internal constant WTSYS_A_TOKEN = 0x2f259e071Ad31684C61dF1df320e624020d88423;

  // https://iotexscan.io/address/0x2f839f081B49e9Fae6d40392424330ea94dDD81e
  address internal constant WTSYS_V_TOKEN = 0x2f839f081B49e9Fae6d40392424330ea94dDD81e;

  // https://iotexscan.io/address/0x108d4F4B79FDea3a1413B70F97ed3a4E570bB046
  address internal constant WTSYS_S_TOKEN = 0x108d4F4B79FDea3a1413B70F97ed3a4E570bB046;

  // https://iotexscan.io/address/0xe0eCf2cBA6788EEa8e681746D1e5a3e9283381Db
  address internal constant WTSYS_ORACLE = 0xe0eCf2cBA6788EEa8e681746D1e5a3e9283381Db;

  // https://iotexscan.io/address/0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3
  address internal constant WTSYS_INTEREST_RATE_STRATEGY =
    0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3;

  // https://iotexscan.io/address/0x641c9027E1dB73e40aA1eA8EeE22A3E1c4C86B65
  address internal constant RUSDT_UNDERLYING = 0x641c9027E1dB73e40aA1eA8EeE22A3E1c4C86B65;

  uint8 internal constant RUSDT_DECIMALS = 6;

  // https://iotexscan.io/address/0x2bbD85420B31e0707225D10542ae1366c249349C
  address internal constant RUSDT_A_TOKEN = 0x2bbD85420B31e0707225D10542ae1366c249349C;

  // https://iotexscan.io/address/0xd90596A04b8C5008BeDE13f2632A2a7A6ed374C8
  address internal constant RUSDT_V_TOKEN = 0xd90596A04b8C5008BeDE13f2632A2a7A6ed374C8;

  // https://iotexscan.io/address/0xdC261b798Fbb088e8FdeC272d1a78cFB86320dD9
  address internal constant RUSDT_S_TOKEN = 0xdC261b798Fbb088e8FdeC272d1a78cFB86320dD9;

  // https://iotexscan.io/address/0x1B45DdD14Ba6Eb8f00f2496cf60068AFEc11092F
  address internal constant RUSDT_ORACLE = 0x1B45DdD14Ba6Eb8f00f2496cf60068AFEc11092F;

  // https://iotexscan.io/address/0x94031687971670659b50a0C946711EecFedD6C8E
  address internal constant RUSDT_INTEREST_RATE_STRATEGY =
    0x94031687971670659b50a0C946711EecFedD6C8E;

  // https://iotexscan.io/address/0x514207067DE90a88F37236E404506d341D1ee933
  address internal constant RUSDC_UNDERLYING = 0x514207067DE90a88F37236E404506d341D1ee933;

  uint8 internal constant RUSDC_DECIMALS = 6;

  // https://iotexscan.io/address/0xf38a7C3765043205CED04Db7252909b900c45C1b
  address internal constant RUSDC_A_TOKEN = 0xf38a7C3765043205CED04Db7252909b900c45C1b;

  // https://iotexscan.io/address/0xD9d56d250789eB19fD74728A6646eDDd2b400653
  address internal constant RUSDC_V_TOKEN = 0xD9d56d250789eB19fD74728A6646eDDd2b400653;

  // https://iotexscan.io/address/0x664FB854e27F17E830acb0BfA92F5CF2dB9898BF
  address internal constant RUSDC_S_TOKEN = 0x664FB854e27F17E830acb0BfA92F5CF2dB9898BF;

  // https://iotexscan.io/address/0x758bD351E33B22C04D61874974F23914daCB6AaB
  address internal constant RUSDC_ORACLE = 0x758bD351E33B22C04D61874974F23914daCB6AaB;

  // https://iotexscan.io/address/0x94031687971670659b50a0C946711EecFedD6C8E
  address internal constant RUSDC_INTEREST_RATE_STRATEGY =
    0x94031687971670659b50a0C946711EecFedD6C8E;

  // https://iotexscan.io/address/0x4EbB8B5c866C91f93c5c05747F35C56D85688a66
  address internal constant RPSYS_UNDERLYING = 0x4EbB8B5c866C91f93c5c05747F35C56D85688a66;

  uint8 internal constant RPSYS_DECIMALS = 18;

  // https://iotexscan.io/address/0xf7F5D288241Df90f4317006BD844154aF5f30E4e
  address internal constant RPSYS_A_TOKEN = 0xf7F5D288241Df90f4317006BD844154aF5f30E4e;

  // https://iotexscan.io/address/0x442ea105F093eE0bB2B0fd7D07026A3dc25B5786
  address internal constant RPSYS_V_TOKEN = 0x442ea105F093eE0bB2B0fd7D07026A3dc25B5786;

  // https://iotexscan.io/address/0x416508e07159E3B69B141Ef33E9c7b4AD3a96C2d
  address internal constant RPSYS_S_TOKEN = 0x416508e07159E3B69B141Ef33E9c7b4AD3a96C2d;

  // https://iotexscan.io/address/0x3eD5FcD97f7aEe70fD0128758973a9F01210af0D
  address internal constant RPSYS_ORACLE = 0x3eD5FcD97f7aEe70fD0128758973a9F01210af0D;

  // https://iotexscan.io/address/0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3
  address internal constant RPSYS_INTEREST_RATE_STRATEGY =
    0x765b80df1B7B1671D2B3dC112aAc15eC3A06F7f3;
}

library AaveV3TinkleEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant STABLECOINS = 1;
}
