// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {AaveV1} from './AaveV1.sol';
import {AaveV3Tinkle} from './AaveV3Tinkle.sol';
import {AaveV3Tanenbaum} from './AaveV3Tanenbaum.sol';
import {AaveGovernanceV2} from './AaveGovernanceV2.sol';
import {AaveSafetyModule} from './AaveSafetyModule.sol';
